Repository For-Hives/api-my-makeup, pull requests merged in 2023-04, with the labels that each got.

#13 feat(#10): ajout connecteur S3
  .env.example
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-only.yml
  .gitignore
  README.md
  config/middlewares.js
  config/plugins.js
  package.json
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
  yarn.lock
Labels: enhancement

#26 🐛 fix(database.js): add pool configuration to database configuration
  config/database.js
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
Labels: bug

#27 ✨ feat(init-makeup): add init-makeup endpoint to create a new makeup …
  src/api/makeup-artiste/content-types/makeup-artiste/schema.json
  src/api/makeup-artiste/controllers/init-makeup.js
  src/api/makeup-artiste/routes/init-makeup.js
  src/api/makeup-artiste/services/init-makeup.js
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
  src/extensions/documentation/public/index.html
Labels: enhancement

#29 🚧 refactor(#24): déplacer l'attribut "language" dans un co…
  src/api/makeup-artiste/content-types/makeup-artiste/schema.json
  src/components/makeupartists/language.json
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
Labels: bug

#40 Update renovate.json
  renovate.json
Labels: feature

#43 🐛 fix(#38): disable draft and publish option in schema.json
  src/api/makeup-artiste/content-types/makeup-artiste/schema.json
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
Labels: bug

#44 🚀 chore(#30): rename build step to 'Try Building image' and add 'Unit Test' step
  .github/workflows/build-only.yml
Labels: bug

#35 feat(#34) : ✨ ajouter la fonctionnalité de recherche de maquillage
  package.json
  src/api/searching/controllers/searching.js
  src/api/searching/documentation/1.0.0/searching.json
  src/api/searching/routes/searching.js
  src/api/searching/services/searching.js
Labels: feature

#46 feat(#45) : 🔨 ajouter la fonctionnalité meMakeup
  src/api/makeup-artiste/controllers/init-makeup.js
  src/api/makeup-artiste/routes/init-makeup.js
  src/api/makeup-artiste/services/init-makeup.js
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
Labels: feature

#52 feat(#50): Traitement des tickets, changement des tailles de champs de textes
  src/api/makeup-artiste/content-types/makeup-artiste/schema.json
  src/components/makeupartists/experiences.json
  src/components/makeupartists/service-offers.json
  src/components/service-offers/options.json
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
Labels: feature

#54 feat(#53): Supprimer la partie frais kilométriques
  src/api/makeup-artiste/content-types/makeup-artiste/schema.json
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
Labels: feature

#56 feat(#55): Ajouter le numéro de tel & le lien vers linkedin
  src/api/makeup-artiste/content-types/makeup-artiste/schema.json
  src/components/makeupartists/network.json
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
Labels: feature

#59 fix(#58): 🐛 ajouter la fonctionnalité de population des relations dans la requête de recherche
  src/api/makeup-artiste/services/init-makeup.js
  src/api/searching/services/searching.js
  src/components/makeupartists/service-offers.json
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
Labels: bug

#60 fix(#58): ajouter la population des champs manquants dans la méthode getMakeupById
  src/api/makeup-artiste/services/init-makeup.js
Labels: bug
