Repository For-Hives/api-my-makeup, pull requests merged in 2023-05, with the labels that each got.

#61 fix(#58): ajouter la population des champs manquants
  src/api/makeup-artiste/services/init-makeup.js
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
Labels: bug

#65 fix(#64): 🐛 mettre à jour les données de mise à jour du maquilleur
  src/api/makeup-artiste/services/init-makeup.js
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
Labels: bug

#66 🔥 refactor(makeup-artiste.js) : supprimer une ligne vide à la fin du fichier
  src/api/makeup-artiste/content-types/makeup-artiste/schema.json
  src/components/makeupartists/network.json
  src/components/makeupartists/skills.json
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
Labels: feature

#57 refacto(): 🚨 retourner le premier élément du tableau existing
  Dockerfile
  package-lock.json
  package.json
  src/api/makeup-artiste/controllers/me-makeup.js
  src/api/makeup-artiste/documentation/1.0.0/me-makeup.json
  src/api/makeup-artiste/routes/me-makeup.js
  src/api/makeup-artiste/services/me-makeup.js
  src/api/searching/controllers/searching.js
  src/api/searching/services/searching.js
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
  src/extensions/documentation/public/index.html
  tests/app.test.js
  tests/controllers/my-makeup/index.js
  tests/controllers/user/index.js
  tests/helpers/strapi.js
  tests/services/me-makeup/me-makeup.test.js
  tests/services/serching/search.test.js
Labels: bug, documentation

#68 feat(#67): ✨ ajouter la recherche de maquilleurs en fonction de plusieurs critères de recherche
  src/api/searching/controllers/searching.js
  src/api/searching/services/searching.js
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
  tests/services/serching/search.test.js
Labels: feature

#70 fix(#69): 🚀 ajouter des filtres pour les images, la langue et la galerie d'images
  src/api/searching/services/searching.js
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
Labels: bug

#75 fix(#74): 🔧 ajouter des valeurs par défaut pour les champs spécialité, description et réseau
  src/api/makeup-artiste/content-types/makeup-artiste/schema.json
  src/api/makeup-artiste/services/me-makeup.js
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
Labels: bug
