Repository For-Hives/api-my-makeup, pull requests merged in 2023-06, with the labels that each got.

#79 feat(#76): Ajout d'une partie "article" pour le blog de my makeup
  .gitignore
  src/api/article/content-types/article/schema.json
  src/api/article/controllers/article.js
  src/api/article/documentation/1.0.0/article.json
  src/api/article/routes/article.js
  src/api/article/services/article.js
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
  src/extensions/documentation/public/index.html
Labels: feature

#81 fix(#80):🔥supprimer les champs first_name et last_name
  src/api/makeup-artiste/services/me-makeup.js
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
Labels: bug

#84 fix(#83): 🔧renommer la propriété 'score' en 'search_score' et ajouterla propriété 'user' dans la requête de recherche
  src/api/searching/services/searching.js
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
  tests/services/serching/search.test.js
Labels: bug

#86 feat(#85): ✨ ajouter le champ username
  src/api/makeup-artiste/content-types/makeup-artiste/schema.json
  src/api/makeup-artiste/services/me-makeup.js
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
Labels: feature

#88 feat(#87): Créer la partie "Talents" pour gérer les spécialités (seo)
  src/api/talent/content-types/talent/schema.json
  src/api/talent/controllers/talent.js
  src/api/talent/documentation/1.0.0/talent.json
  src/api/talent/routes/talent.js
  src/api/talent/services/talent.js
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
Labels: feature

#91 Feat(#90): add pro boolean to makeup artist
  src/api/makeup-artiste/content-types/makeup-artiste/schema.json
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
Labels: feature

#94 Feat(#93): add company name to the fields in makeup artist
  src/api/makeup-artiste/content-types/makeup-artiste/schema.json
  src/extensions/documentation/documentation/1.0.0/full_documentation.json
Labels: bug, feature
